// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfjb_RBZKNo8FAAwZ1SpscNZ8WiCsBuEE',
    appId: '1:1035170954270:web:40ae9a5e3e1c14910e420f',
    messagingSenderId: '1035170954270',
    projectId: 'mahatati-74c8a',
    authDomain: 'mahatati-74c8a.firebaseapp.com',
    storageBucket: 'mahatati-74c8a.appspot.com',
    measurementId: 'G-R7XQL1FG0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6vwtZO5vqE7Ttf9oAgUu4ewLN-Tras_U',
    appId: '1:1035170954270:android:c9f8669579fc123e0e420f',
    messagingSenderId: '1035170954270',
    projectId: 'mahatati-74c8a',
    storageBucket: 'mahatati-74c8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVvet6UcSZNxpNVYAjo4xDUmBxzb_xsaU',
    appId: '1:1035170954270:ios:0db39e6b5efbfa8b0e420f',
    messagingSenderId: '1035170954270',
    projectId: 'mahatati-74c8a',
    storageBucket: 'mahatati-74c8a.appspot.com',
    iosBundleId: 'com.mahatati.maher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVvet6UcSZNxpNVYAjo4xDUmBxzb_xsaU',
    appId: '1:1035170954270:ios:9b99be89642a07e70e420f',
    messagingSenderId: '1035170954270',
    projectId: 'mahatati-74c8a',
    storageBucket: 'mahatati-74c8a.appspot.com',
    iosBundleId: 'com.example.fullcodetop.RunnerTests',
  );
}
